naver:
  fortune:
    apiUri: https://search.naver.com/search.naver?query=

hash:
  salt: hodolee

spring:
  datasource:
    url: jdbc:h2:./circuit
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  data:
    redis:
      host: redis
      port: 6379

fortune:
  default-message: "오늘 하루 좋을예정"

redis:
  address: redis://localhost:6379

  kafka:
    bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    group-id: fortune-view
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topic: fortune-view-topic